# Generated by Django 3.2.4 on 2021-06-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
